### ISSUE TITLE
resolv.conf lost in some situation

### ISSUE THREAD

**Issue by duck-rh** [NLnetLabs/dnssec-trigger#3]
Quack,

At Devconf.cz and some hotel there were WIFI portals with authentication, nothing uncommon. I then used `dnssec-trigger-control hotspot_signon` to be able to reach the portal but the address could not be resolved. I forgot to capture the logs at the time but got a similar problem at CfgMgmt and captured it. Aside from some error that may cause the WIFI DNS to be considered unsecure by mistake, the error is exactly the same: the unsafe resolv.conf configuration was not saved properly in '/run/dnssec-trigger/' for some reason and cannot be restored; this leads to /etc/resolv.conf to simply be removed and nothing works.

Regards.

[dnssec-trigger_login_portal_bug.log](https://github.com/NLnetLabs/dnssec-trigger/files/4147103/dnssec-trigger_login_portal_bug.log)

**Comment by wcawijngaards** [comment]
Hi Duck-rh,
The fix in https://github.com/NLnetLabs/dnssec-trigger/commit/f187c2be221a26f3c4ef4d9b16f1df67104ae634 may help.  It fixes the not allowed character errors. The `@` character gets allowed as it looks to be used to specify a port number, which should be on the allowed list.  The fix is easy to code, I have not been able to test this, but perhaps it can work for you. Thanks for the report!
Best regards, Wouter

**Comment by duck-rh** [comment]
thanks @wcawijngaards this fixed the error. I'll try to test in other environments.
